### ISSUE TITLE
SPERG Mod Analysis Fails in 1.7

### ISSUE THREAD

**Issue by KerningChameleon** [matortheeternal/mod-analyzer#11] opened 2016-11-17 08:21 UTC
Attempted to Analyze [SPERG -- Skyrim Perk Enhancements and Rebalanced Gameplay](http://www.nexusmods.com/skyrim/mods/24445) on Windows 10 64-bit (1607) through Mod Organizer v1.3.11 with Mod Analyzer 1.7 (and previously, 1.6). Analysis fails with this output:

> Analyzing SPERG 4 0-24445-4-0.7z...
> Calculating MD5 Hash.
> Parsing FOMOD Options
> Found FOMOD Config at [fomod/ModuleConfig.xml]
> FOMOD Config Extracted
> 
> Object reference not set to an instance of an object.
> Analysis failed

**Comment by matortheeternal** [comment] 2016-11-21 05:33
Thanks for the report, will look into it!

**Comment by KerningChameleon** [comment] 2016-11-29 12:47
Given the update notes, you probably already tested this, but just in case, here's how the exception looks now in 1.7.2 with the stack trace logging:

> Analyzing SPERG 4 0-24445-4-0.7z...
> Calculating MD5 Hash.
> Parsing FOMOD Options
> Found FOMOD Config at fomod/ModuleConfig.xml
> FOMOD Config Extracted
> 
> Object reference not set to an instance of an object.
>    at ModAnalyzer.Domain.FomodFile..ctor(XmlNode node)
>    at ModAnalyzer.Domain.FomodFile.FromNodes(XmlNodeList nodes)
>    at ModAnalyzer.Domain.FomodConfig.GetBaseFiles(XmlDocument doc)
>    at ModAnalyzer.Domain.FomodConfig..ctor(String xmlPath)
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeFomodArchive(IArchive archive)
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeArchive(IArchive archive, ModOption modOption)
>    at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
> Analysis failed.

**Comment by matortheeternal** [comment] 2016-12-08 02:26
This will probably be resolved in the next version, but I need to test to make certain.

**Comment by KerningChameleon** [comment] 2016-12-09 02:21
Results with 1.8.1 are... inconclusive. Obviously, analyzing as a FOMOD fails:

> Analyzing SPERG 4 0-24445-4-0.7z...
> Calculating MD5 Hash.
> Parsing FOMOD Options
> Found FOMOD Config at fomod\ModuleConfig.xml
> FOMOD Config Extracted
> 
> Object reference not set to an instance of an object.
>    at ModAnalyzer.Domain.FomodFile..ctor(XmlNode node)
>    at ModAnalyzer.Domain.FomodFile.FromNodes(XmlNodeList nodes)
>    at ModAnalyzer.Domain.FomodConfig.GetBaseFiles(XmlDocument doc)
>    at ModAnalyzer.Domain.FomodConfig..ctor(String xmlPath)
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeFomodArchive(ModOption archiveModOption)
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeArchive(ModOption modOption)
>    at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
> Analysis failed.

Analyzing as a BAIN succeeds... but I'm not sure it actually analyzed the SPERG.esm and esp. It seemed to treat the folder called SPERG  (which is where are the optional plugins are stored) as the Data directory and ignored everything above it... which is where the actual default plugins are.

I submitted the analysis file with the Mod Picker submission, but it might actually be an Incomplete Analysis. Sorry, I wasn't quite sure how to resolve the situation. At least you can review an actual json output file now?

**Comment by matortheeternal** [comment] 2016-12-09 09:19
Thanks, yeah I'm going to look into it.  I imagine that it's probably another FOMOD XML parsing issue.  I need to make the code a bit more strict.

**Comment by matortheeternal** [comment] 2016-12-28 02:55
It looks like this was resolved?  SPERG is submitted to Mod Picker: https://modpicker.com/skyrim#/mod/980

**Comment by matortheeternal** [comment] 2016-12-28 03:06
OK, it looks like the issue is still present.  Not sure how CoyoteSans managed to generate an analysis for it.  I'm looking into the issue now and will push a hotfix once I've isolated the issue and resolved it.

**Comment by matortheeternal** [comment] 2016-12-28 03:12
Alright, found the source of the problem and analyzed SPERG successfully.  Pushing hotfix release.

**Closed as completed by matortheeternal** 2016-12-28 03:12 UTC
Labels: bug
